### ISSUE TITLE
Version 5 errors with File not found: 'D:\a\_tasks\GitTag_be6aa0ca-e62f-414d-aaa6-e9524b556482\5.0.0\tagging.js'

### ISSUE THREAD

**Issue by danielearwicker** [ReneSorensen/VSTSTools#24]
If I select version 4 it gets further, but still fails in trying to get the access token. As seen in issue #22 - I want to use YAML and thought I needed to use version 5.0 to get around that issue.

How do I get a working version?

**Comment by VisualBean** [comment]
@ReneSorensen - I see changes made recent -ish
And I do not own any of these extensions any more. Please look into it.

**Comment by ReneSorensen** [comment]
Hi Daniel
Sorry for all the problems I've made. I had trouble with node, npm, ts,
version etc. Did not discover at first, lesson learned remember test.
I have made a new fix, 5.0 should work now.
Sincerely
René

Den ons. 5. dec. 2018 kl. 18.24 skrev Daniel Earwicker <
notifications@github.com>:

**Comment by Tankatronic** [comment]
@ReneSorensen version 5.0 is still broken with the same error
 `##[error]File not found: 'D:\a\_tasks\GitTag_be6aa0ca-e62f-414d-aaa6-e9524b556482\5.0.0\tagging.js'`

**Comment by Tankatronic** [comment]
I am sure this will be resolved soon, but in the meantime there's a workaround for those who are using YAML builds. Specify @4 for version 4 and the environment variable for the system access token, followed by any other inputs you may have and you are all set.

```
- task: ATP.ATP-GitTag.GitTag.GitTag@4
  displayName: 'GitTag '
  env:
    system_accesstoken: $(System.AccessToken)
```

**Comment by ReneSorensen** [comment]
Hi
I changed the version number to 5.1, now it works.
I thought you only need updating code, not version
René

**Comment by ReneSorensen** [comment]
new fix, 5.1
